title: Chengchen Zhou's website
page-top-title: Welcome to my website!
top-section-bg-text: MscCT+
home-subtitle: Chengchen Zhou&ensp;|&ensp;周程晨
copyright-text: '&copy; Chengchen Zhou 2000-2024. Hello, it's just a test ^^ relax~'
